### ISSUE TITLE
Support for german client

### ISSUE THREAD

**Issue by luitzifa** [Chalos-Atiesh/GuildTradeskills#54]
Hi,

i'm from a german guild and most of my guild members are playing with a german client.
When they try to add a profession they get somthing like "Schmiedekunst ist nicht supported"
Schmiedekunst = Blacksmithing

**Comment by Chalos-Atiesh** [comment]
Hello! Thanks for filing this!
We added some limitations on what specific tradeskills someone can add so that Smelting, Skinning, etc. don't make their way into the addon.
This is where it gets interesting. That string is one in the localization file that reads '{tradeskill_name} is not supported'. So you should be seeing the english version unless it's being auto-translated somehow. Are you seeing it in english or german?
If you're seeing it in german would you mind zipping the addon, uploading it to your preferred file sharing service, and sending us a link to it?
Unfortunately my german is not nearly enough up to par to be able to provide an adequate translation for the app.

**Comment by luitzifa** [comment]
Hey thanks for your fast response.
As i'm just the messenger, i cannot really quote the Error. That was just what my guild members told me via Teamspeak. I'm quite sure they autotranslated it in their head, when telling me.

Then why do i report this? They are not really into programming / github.

So, when i understand you right, i just need to provide german translation then? I'll try to!

**Comment by Chalos-Atiesh** [comment]
I will go ahead and warn you that there are probably far more strings than you think but if you want to take a stab at it we'd be very grateful. You can find all the english localized strings here:
https://github.com/Chalos-Atiesh/GuildTradeskills/blob/master/locale/localization.en.lua
To create a new localization copy that to a new file named 'localization.de.lua' and provide the german translations in that new file. Please do not translate anything between '{{' and '}}' as that is replaced by the addon.

**Comment by luitzifa** [comment]
Thanks for the advise. I just pushed a work in progress. So far all string are translated but the wording and spelling needs some improvement. Not worth a mergerequest yet. And it's not even testet for now, hope some guild collogues can help with that later.

**Comment by luitzifa** [comment]
I left some of the strings original, because it would lead to strange commands like:
```
/gt reset bestätige
```

In fact, most germans are quite ok with english, so i see no realy dealbreaker with this.

**Comment by Chalos-Atiesh** [comment]
So far it looks good to me. Thank you! Issue a PR whenever you're ready and I'll merge and push an update with the removeprofession fix.

**Comment by luitzifa** [comment]
PR provided. Thank you!

**Comment by StephanDufour** [comment]
Same thing for the french version.

**Comment by Chalos-Atiesh** [comment]
This should be fixed with 6.0.2

**Comment by luitzifa** [comment]
thanks
